[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn server:app --bind 0.0.0.0:$PORT --timeout 600 --workers 2"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/health"
timeout = 300
